---
engines:
  tsqllint:
    enabled: true
ignore:
  - tsqllint:
      - "TSQLLint_data-compression"
      - "TSQLLint_set-quoted-identifier"
exclude_paths:
  - "apps/control-plane/drizzle/**"
  - "apps/marketing/migrations/**"
