import {
  formatHex,
  wcagContrast,
  modeOklch,
  modeRgb,
  useMode,
  interpolate,
  type Color,
} from "culori";

const oklch = useMode(modeOklch);
const rgb = useMode(modeRgb);

/**
 * Generates a full HeroUI (NextUI) color palette (50-900) from a single base color.
 * The 500 shade is the base color.
 * Shades 50-400 are generated by mixing with white.
 * Shades 600-900 are generated by mixing with black.
 *
 * @param baseColor - The hex or rgb string of the base color
 * @returns A record containing shades from 50 to 900
 */
export function generateHeroUIPalette(baseColor: string) {
  let color: Color | undefined;
  try {
    color = oklch(baseColor);
  } catch {
    // Invalid color
  }

  if (!color) {
    // eslint-disable-next-line no-console
    console.warn(`Invalid color: ${baseColor}. Returning fallback palette.`);
    return {
      50: "#f9fafb",
      100: "#f3f4f6",
      200: "#e5e7eb",
      300: "#d1d5db",
      400: "#9ca3af",
      500: "#6b7280",
      600: "#4b5563",
      700: "#374151",
      800: "#1f2937",
      900: "#111827",
    };
  }

  const palette: Record<number, string> = {};

  // We use OKLCH for better interpolation results
  const white = oklch("#ffffff")!;
  const black = oklch("#000000")!;

  // Interpolators
  const tint = interpolate([white, color], "oklch"); // White to Color
  const shade = interpolate([color, black], "oklch"); // Color to Black

  // Ratios for mixing
  // 50: 95% white -> 0.05 on the white-to-color scale
  // ...
  // 500: base color
  // ...
  // 900: 60% black -> 0.4 on the color-to-black scale

  palette[50] = formatHex(tint(0.05))!;
  palette[100] = formatHex(tint(0.1))!;
  palette[200] = formatHex(tint(0.25))!;
  palette[300] = formatHex(tint(0.4))!;
  palette[400] = formatHex(tint(0.7))!;
  palette[500] = formatHex(color)!;
  palette[600] = formatHex(shade(0.15))!;
  palette[700] = formatHex(shade(0.3))!;
  palette[800] = formatHex(shade(0.45))!;
  palette[900] = formatHex(shade(0.6))!;

  return palette;
}

/**
 * Determines the best foreground color (white or black) for a given background color
 * based on contrast ratios (W3C recommendation).
 *
 * @param backgroundColor - The hex or rgb string of the background color
 * @returns '#ffffff' or '#000000'
 */
export function getContrastColor(backgroundColor: string): string {
  // Convert to RGB for WCAG contrast calculation as per standard
  // culori handles parsing
  const bg = rgb(backgroundColor);
  if (!bg) return "#ffffff";

  const white = rgb("#ffffff")!;
  const black = rgb("#000000")!;

  const whiteContrast = wcagContrast(bg, white);
  const blackContrast = wcagContrast(bg, black);

  return whiteContrast > blackContrast ? "#ffffff" : "#000000";
}
